[package]
name = "crdt-range"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crdt-list = { version = "0.4.1", optional = true, features = ["fuzzing"] }
rand = { version = "0.8.5", optional = true }
enum-as-inner = "0.5.1"

[features]
test = ["crdt-list", "rand"]

[dev-dependencies]
arbtest = "0.2.0"
